version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-xe-db
    environment:
      ORACLE_PASSWORD: OraclePassword123
      ORACLE_DATABASE: XEPDB1
      ORACLE_USERNAME: devuser
      ORACLE_USER_PASSWORD: DevPassword123
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db-init-scripts:/container-entrypoint-initdb.d
      - ./db-data:/opt/oracle/import
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  # Web interface - CloudBeaver (DBeaver web interface with Oracle support)
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: oracle-cloudbeaver
    ports:
      - "8081:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - oracle-db
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local
  cloudbeaver-data:
    driver: local

networks:
  default:
    name: oracle-network