services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-xe-db
    environment:
      ORACLE_PASSWORD: OraclePassword123
      ORACLE_DATABASE: XEPDB1
      ORACLE_USERNAME: devuser
      ORACLE_USER_PASSWORD: DevPassword123
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db-init-scripts:/container-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  oracle-ords:
    image: container-registry.oracle.com/database/ords:latest
    container_name: oracle-ords
    environment:
      CONN_STRING: oracle-db:1521/XEPDB1
      ORACLE_PWD: OraclePassword123
      ORACLE_USER: sys
      ORACLE_ROLE: SYSDBA
    ports:
      - "8081:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local

networks:
  default:
    name: oracle-network