-- Create tables and objects for egf_schema user
-- Connect as egf_schema
CREATE USER EGFDMIS IDENTIFIED BY EgfPass2017;

CREATE OR REPLACE DIRECTORY IMPORT_DIR AS '/opt/oracle/import';

GRANT UNLIMITED TABLESPACE TO EGFDMIS;
GRANT DBA TO EGFDMIS;

GRANT READ, WRITE ON DIRECTORY IMPORT_DIR TO EGFDMIS;

CONNECT EGFDMIS/EgfPass2017@XEPDB1;